### ISSUE TITLE
Firefox 中搜索栏聚焦的毛玻璃效果无效

### ISSUE THREAD

**Issue by WolfLee-red** [hakadao/bilibili-simple-home#11]
Firefox 80.0.1 稳定版
搜索栏聚焦暗化已开启，并显示正常，但毛玻璃效果无效。

**Comment by hakadao** [comment]
火狐的话需要去到`about:config`页面，再搜索`layout.css.backdrop-filter.enabled`和 `gfx.webrender.all preference`并同时设为`true`，再重新打开浏览器页面

**Comment by WolfLee-red** [comment]
很抱歉这么晚才回复。打开 `layout.css.backdrop-filter.enabled` 之后已经正常了，感谢开发者。

**Comment by aboutZZ** [comment]
目前最新版火狐已经支持`backdrop-filter`了，无需手动开启
