### ISSUE TITLE
官方新头图banner导致自定义背景无效

### ISSUE THREAD

**Issue by JesseZhang97** [hakadao/bilibili-simple-home#13]
![image](https://user-images.githubusercontent.com/40453270/94544442-d1dcad00-027d-11eb-81fb-be4f16753ce7.png)

**Comment by hakadao** [comment]
emmm，回去把bug改了

**Comment by flashorsink** [comment]
不知道之前的官方静态图片是不是也能这样完整的显示，能的话建议给个选项，今天这个挺好看的，图片也是完整的而不是拉伸的，刚开始还以为是你出的新动态壁纸hhh

**Comment by hakadao** [comment]
> 不知道之前的官方静态图片是不是也能这样完整的显示，能的话建议给个选项，今天这个挺好看的，图片也是完整的而不是拉伸的，刚开始还以为是你出的新动态壁纸hhh

看情况，不过我觉得发大后的效果挺卡的，不知道日后会不会还是有这种效果

**Comment by flashorsink** [comment]
我这边把样式关了图照样卡，是b站动图的问题



---原始邮件---
发件人: "Hakadao"<notifications@github.com&gt;
发送时间: 2020年9月29日(周二) 晚上9:31
收件人: "hakadao/bilibili-simple-home"<bilibili-simple-home@noreply.github.com&gt;;
抄送: "FLASH"<365396309@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [hakadao/bilibili-simple-home] 官方新头图banner导致自定义背景无效 (#13)




  
不知道之前的官方静态图片是不是也能这样完整的显示，能的话建议给个选项，今天这个挺好看的，图片也是完整的而不是拉伸的，刚开始还以为是你出的新动态壁纸hhh
  
看情况，不过我觉得发大后的效果挺卡的，不知道日后会不会还是有这种效果
