### ISSUE TITLE
Stylus 无法正常更新

### ISSUE THREAD

**Issue by Geeyun-JY3** [hakadao/bilibili-simple-home#14]
如图，提示：
> Stylus 未能成功解析 UserCSS：
无效的版本号. 值与 SemVer 规则不匹配: 1.2

![image](https://user-images.githubusercontent.com/49396421/99261791-26e97800-2858-11eb-9923-6abd3751f0c5.png)
![image](https://user-images.githubusercontent.com/49396421/99261887-408abf80-2858-11eb-84a9-73a2de5b8b3d.png)

**Comment by hakadao** [comment]
emmmm，我研究下

**Comment by hakadao** [comment]
修復了，應該得了

**Comment by Geeyun-JY3** [comment]
已解决。
