### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RickSanchez-1** [hakadao/bilibili-simple-home#19]
排行榜出现bug不显示图片，然后下面那些间隔都莫名变大 (比如动画与番剧之间)

**Comment by hakadao** [comment]
太不好意思了，最近很忙没有时间打理这个项目，今天我会看一下:cold_sweat:

**Comment by RickSanchez-1** [comment]
没事，反正也不咋用到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月30日(星期五) 晚上6:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hakadao/bilibili-simple-home] BUG (#19)





 
太不好意思了，最近很忙没有时间打理这个项目，今天我会看一下😰

**Comment by hakadao** [comment]
已修正

**Comment by qq1840083132** [comment]
没有办法更新,点击更新还是1.2.1版本

**Comment by qq1840083132** [comment]
> 已修正
没有办法更新,点击更新还是1.2.1版本

**Comment by ZhangTianrong** [comment]
> 没有办法更新,点击更新还是1.2.1版本

我这边本来想打开raw复制的，结果打开之后就自动提示更新了，你可以试试。

**Comment by qq1840083132** [comment]
> > 没有办法更新,点击更新还是1.2.1版本
> 
> 我这边本来想打开raw复制的，结果打开之后就自动提示更新了，你可以试试。

确实还是不行,我这里显示1.2.1就是最新版本,点击首页的更新链接也只有重新安装1.2.1.

**Comment by hakadao** [comment]
@ZhangTianrong 更新有延迟很正常，走CDN。毕竟不是任何人能访问raw
