### ISSUE TITLE
聚焦有问题

### ISSUE THREAD

**Issue by flashorsink** [hakadao/bilibili-simple-home#2]
点击右上链接时（就是头像旁边的消息，动态等）也会触发聚焦

**Comment by flashorsink** [comment]
另外希望搜索结束后解除聚焦效果

**Comment by hakadao** [comment]
確實是個bug，`:focus-within`寫的位置問題，另外搜索後解除聚焦是要怎麼觸發？回車消失？

**Comment by flashorsink** [comment]
我不是很懂软件编程只能说说现象，我试了下暂时发现的有三种1.回车2.点击搜索按钮3.点击搜索的联想内容，还有一种方案是有页面被新建跳转了就取消聚焦。

**Comment by flashorsink** [comment]
另外再反馈一个bug，页面缩小的的时候头像旁边会有一个小搜索图标
![@G6%J 2M07KJ% (IXAD_LMN](https://user-images.githubusercontent.com/23011333/88020969-392fff80-cb5f-11ea-9203-7e1fdc307288.png)

**Comment by hakadao** [comment]
谢谢提出bug，css也不叫编程（个人认为），1.回车2.点击搜索按钮3.点击搜索的联想内容取消聚焦单靠css有点难以实现。话说bing的是直接从当前页面跳转的，国内大多数网站都是新开一个页面再跳转，css是不能做到改成单页面跳转的

**Comment by flashorsink** [comment]
不需要改为单页面跳转，我的意思是能不能以新开页面为触发条件来关闭聚焦，这样就不需要判断这么多了。

**Comment by hakadao** [comment]
更新了聚焦触发位置，点击右上现在应该不会触发了。页面缩小的搜索图标也修复了

**Comment by flashorsink** [comment]
还有一个关于聚焦的小bug，搜索后随便点击一个地方，搜索框失去焦点聚焦效果解除了，但是历史搜索栏不会关闭，还要再点一下才会收起。能不能在聚焦解除的时候关闭历史搜索栏？

**Comment by hakadao** [comment]
emmm，我一会看看

**Comment by flashorsink** [comment]
感谢感谢，打算长期使用的所以对小问题很在意，麻烦了

**Comment by hakadao** [comment]
修复了，你看看

**Comment by flashorsink** [comment]
顶部链接效果二自带了很黑的遮罩效果，以前没有问题
```
.bili-banner .taper-line {
    background: none!important;
} EOT;
TOPLINK_2 "效果2（推荐自定义背景使用）" <<<EOT
.bili-banner .taper-line {
  background-image: radial-gradient(
      rgba(0, 0, 0, 0) 0%,
      rgba(0, 0, 0, 0.5) 100%       //这行的锅这行的锅这行的锅这行的锅
    ),
radial-gradient(rgba(0, 0, 0, 0) 33%, rgba(0, 0, 0, 0.3) 166%) !important;
height: 100% !important;
}
 EOT;
}
```

**Comment by hakadao** [comment]
我只是把edge的主页遮罩拿了过来

**Comment by flashorsink** [comment]
要是edge的主页好看就不会有infinity了，而且原来已经有白色可调遮罩了替换那个选项比较好吧。个人认为在有大片白色元素的地方对部分元素用太黑的遮罩对比度太强且让页面信息量缺少了。当然这不算什么问题，个人看法而已。
