### ISSUE TITLE
LOGO不见啦？！

### ISSUE THREAD

**Issue by Waoap** [hakadao/bilibili-simple-home#20]
如图 0.0
好像是图床链接挂了吧
![image](https://user-images.githubusercontent.com/51262009/117140469-07331580-ade0-11eb-8e4d-e561e9e8d0ae.png)
![image](https://user-images.githubusercontent.com/51262009/117140475-08fcd900-ade0-11eb-968a-3d74e736fc7e.png)

**Comment by hakadao** [comment]
試了一下，並沒有出現類似情況，應該時logo沒有加載

**Comment by Waoap** [comment]
一直加载不出来 0.0

**Comment by hakadao** [comment]
> 一直加载不出来 0.0

切換圖標後有顯示嗎

**Comment by hakadao** [comment]
![image](https://user-images.githubusercontent.com/33394391/117387972-68600380-af1c-11eb-98cb-2c205c738c1b.png)
我這裏有顯示

**Comment by Waoap** [comment]
> ![image](https://user-images.githubusercontent.com/33394391/117387972-68600380-af1c-11eb-98cb-2c205c738c1b.png)
> 我這裏有顯示

还是没有~
看样子是我这边的问题趴
我研究研究 <(＿　＿)>

**Comment by Waoap** [comment]
> ![image](https://user-images.githubusercontent.com/33394391/117387972-68600380-af1c-11eb-98cb-2c205c738c1b.png)
> 我這裏有顯示

等下！现在有了！ 大概是因为挂着代理...
（但前几天我明明是关着测试的 0.0）

**Comment by hakadao** [comment]
@Waoap 回去我試試是不是sb GFW的問題

**Comment by Waoap** [comment]
> @Waoap 回去我試試是不是sb GFW的問題

有的时候会这样 emm

![image](https://user-images.githubusercontent.com/51262009/117575127-0fa68b80-b113-11eb-8e25-14d93264b057.png)

![image](https://user-images.githubusercontent.com/51262009/117575111-01586f80-b113-11eb-8432-b5b9d9cf4163.png)

**Comment by Waoap** [comment]
> @Waoap 回去我試試是不是sb GFW的問題

不挂代理还是这样。。。

![image](https://user-images.githubusercontent.com/51262009/117575192-5a280800-b113-11eb-9803-5dcbad6bdc6d.png)

**Comment by Waoap** [comment]
> @Waoap 回去我試試是不是sb GFW的問題

试完了，就是！〒▽〒
