### ISSUE TITLE
自定义背景被刷掉

### ISSUE THREAD

**Issue by 124770049** [hakadao/bilibili-simple-home#23]

**Comment by hakadao** [comment]
能描述下具体怎样触发bug？

**Comment by 124770049** [comment]
自定义背景后打开哔哩哔哩，自动把我的背景刷新成一个gif动画



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月12日(星期一) 中午11:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hakadao/bilibili-simple-home] 自定义背景被刷掉 (#23)





 
能描述下具体怎样触发bug？

**Comment by hakadao** [comment]
晚点我试试

**Comment by 124770049** [comment]
嗯嗯好的，麻烦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月12日(星期一) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hakadao/bilibili-simple-home] 自定义背景被刷掉 (#23)





 
晚点我试试

**Comment by hakadao** [comment]
你是啓用了這個功能嗎？如果是請禁用
![image](https://user-images.githubusercontent.com/33394391/125320326-2d3fdd80-e36e-11eb-8e3f-cbc052e28f58.png)

**Comment by 124770049** [comment]
嗯嗯，解决了，谢谢哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 凌晨0:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hakadao/bilibili-simple-home] 自定义背景被刷掉 (#23)






你是啓用了這個功能嗎?如果是請禁用


—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
