### ISSUE TITLE
首页样式-全屏显示壁纸时元素宽度问题导致出现横向滚动条

### ISSUE THREAD

**Issue by D-Jancy** [hakadao/bilibili-simple-home#28]
在**首页样式**选择**全屏显示壁纸**时, 因为`.center-search-container`这个元素的宽度没有做限制, 会导致页面出现横向滚动条, 影响美观.
在**高级选项**中(即`FULL_HOME "全屏显示壁纸，不能下滑查看更多视频" <<<EOT`后面)添加以下代码即可解决
```JavaScript
.bili-header .bili-header__bar .center-search-container{
	width : 100%!important;
}

**Comment by hakadao** [comment]
已修正
