### ISSUE TITLE
标题没有显示Blibili显示大写的A

### ISSUE THREAD

**Issue by iyyang** [hakadao/bilibili-simple-home#31]
![image](https://user-images.githubusercontent.com/56711789/153918338-e80ff2ff-c9fb-467f-bde0-a9be837bf322.png)

**Comment by iyyang** [comment]
请问这是什么原因

**Comment by hakadao** [comment]
相當於我是用了a來做logo字體，處理方式我再研究下:open_mouth:

**Comment by iyyang** [comment]
> 
好的

**Comment by hakadao** [comment]
請問是一直沒有顯示嗎，還是顯示了一下A後面顯示回logo？

**Comment by iyyang** [comment]
> 

不好意思，忘了回复了，昨天晚上加载完也还是一直显示A，现在又可以正常显示logo了😂
