### ISSUE TITLE
这个logo能隐藏吗，遮挡图片，而且图片显示不全，只有一部分

### ISSUE THREAD

**Issue by liuixm** [hakadao/bilibili-simple-home#32]
![image](https://user-images.githubusercontent.com/76585852/155455362-2b94b738-c2b9-4077-b1ba-78b800598fb4.png)

**Comment by hakadao** [comment]
可以，下版本將嘗試

**Comment by hakadao** [comment]
新版本已添加相應功能，`是否显示 LOGO`

**Comment by liuixm** [comment]
> 新版本已添加相應功能，`是否显示 LOGO`

那个背景图·显示不全能修一下吗，就我上面的图片里，2233有一个没有头露出来

**Comment by hakadao** [comment]
首頁樣式還有幾個選項，這個是專門為風景圖設計的
