### ISSUE TITLE
加载时候的背景能否更改

### ISSUE THREAD

**Issue by Septilliony** [hakadao/bilibili-simple-home#33]
图一：正在加载时的图片
![image](https://user-images.githubusercontent.com/52767905/158800998-15a77473-d726-41f0-9298-a8f6d301c98a.png)

图二：加载完的状态
![image](https://user-images.githubusercontent.com/52767905/158801085-6af21886-9f26-4503-a88d-640717cf85ec.png)

可以删掉图一的加载的那个丑丑的绿色图片吗？或者改为纯色？

**Comment by hakadao** [comment]
我更新了，不知道你收到推送沒
