### ISSUE TITLE
白屏问题

### ISSUE THREAD

**Issue by RickSanchezy** [hakadao/bilibili-simple-home#34]
白屏只有搜索框和bilibili图标，无法下滑（edge浏览器，stylus）

**Comment by hakadao** [comment]
可以發下圖片嗎？還有設定項？

**Comment by RickSanchezy** [comment]
![~}`OVV`NYJXCS_APYPSJ~@L](https://user-images.githubusercontent.com/75956223/161413411-0c5d92f3-bbd8-4c95-a8e9-5e37d263fe25.png)

**Comment by hakadao** [comment]
可能需要在 `选择背景` 里面重新选择一次 `自定义` 的选项才有自定义背景效果
无法下滑是因为在 `首页样式` 中选择了 `全屏显示壁纸，不能下滑查看更多视频` 选项
