### ISSUE TITLE
全屏模式下点一下空白区域搜索栏、logo等就会消失

### ISSUE THREAD

**Issue by mokoopora** [hakadao/bilibili-simple-home#35]
![屏幕截图 2022-04-04 143142](https://user-images.githubusercontent.com/31821836/161486345-b40bf5dd-81f4-446e-b095-cb43b2da4a45.png)
![屏幕截图 2022-04-04 143156](https://user-images.githubusercontent.com/31821836/161486350-e8b142a8-697f-4c49-a6e1-dd12afee6dcf.png)
版本是1.6.11

**Comment by mokoopora** [comment]
![image](https://user-images.githubusercontent.com/31821836/161486502-91794cc3-9eef-4baa-902b-7780b925070a.png)
似乎是叔叔又搞了个什么乱七八糟的活，把搜索栏啥的整没了

**Comment by ZhangPH-9** [comment]
我也想反馈这个情况

**Comment by hakadao** [comment]
我回去看看，這個應該是b站彩蛋

**Comment by hakadao** [comment]
v1.6.12 已经修正此问题
