### ISSUE TITLE
无论什么网站，stylus上总显示该样式匹配

### ISSUE THREAD

**Issue by FrozenBicycle** [hakadao/bilibili-simple-home#37]
1. 无论什么网站，stylus上总显示该样式匹配，如图：
  - ![stylus-1.png](https://s2.loli.net/2022/04/14/nMxmaJbGVXf6doi.png)

2. 我担心这种行为会降低网页加载速度。
3. 如果在管理器中正则测试，则只会匹配B站。
  - ![stylus-2.png](https://s2.loli.net/2022/04/14/76YwbrCMEDViHsZ.png)
4. 我同时也安装了其他样式，并未出现该问题。

**Comment by FrozenBicycle** [comment]
在不应匹配的网站上确实注入了css样式
![stylus-3.png](https://s2.loli.net/2022/04/14/h7cS9iHrj2byaYX.png)

**Comment by hakadao** [comment]
這問題我今天看一下，抱歉

**Comment by FrozenBicycle** [comment]
我做了以下尝试：
接下来，`bilibili-simple-home` 简称为 `bsh`

| 序号 | 行为 | 结果 |
| :---: | :--- | :--- |
| 1 | 卸载并重装stylus | 问题依然存在 |
| 2 | 安装其他样式 | 并没有**匹配任何网站**的问题 |
| 3 | 将`bsh`的网站匹配规则 (正则) 全部替换为`domain("bilibili.com")` | 问题依然存在 |

**Comment by hakadao** [comment]
我知道問題在哪裏了，今日會更新修正這個問題
