### ISSUE TITLE
当前版本（1.6.14）下首页样式有bug

### ISSUE THREAD

**Issue by Seameee** [hakadao/bilibili-simple-home#38]
当前版本（1.6.14）下首页样式的“全屏显示壁纸，不能下滑查看更多视频”仍然可以下滑。而且分区栏有显示bug，似乎在其他的样式中也会这样。
![image](https://user-images.githubusercontent.com/31821836/165941420-750228f0-03ef-4520-a50d-4bf4464c3a2c.png)
![image](https://user-images.githubusercontent.com/31821836/165941572-2b869847-b52d-4a9d-abe7-5b737891682c.png)

**Comment by hakadao** [comment]
是否在 bilibili evolved 設定了隱藏分區欄？

**Comment by Seameee** [comment]
> 是否在 bilibili evolved 設定了隱藏分區欄？

并没有设定隐藏分区，而且我关闭了其他所有脚本后问题依旧
![image](https://user-images.githubusercontent.com/31821836/165943460-4c0acbc6-d6c3-4159-9c71-0e5720308892.png)

**Comment by Seameee** [comment]
![image](https://user-images.githubusercontent.com/31821836/165943866-5c3b2940-8c66-4706-a059-463dafc4c445.png)
似乎是阿b在内测什么新首页，我退出内测就正常了

**Comment by hakadao** [comment]
新版本修复了 v1.6.15

**Comment by Seameee** [comment]
> 新版本修复了 v1.6.15

感谢
