### ISSUE TITLE
能否支持21:9

### ISSUE THREAD

**Issue by NickPascal-PRO** [hakadao/bilibili-simple-home#40]
样式目前锁定在16：9，如果不行的话，可不可以只是上面图片能横跨全屏

**Comment by hakadao** [comment]
能放一下你那边的效果吗？

**Comment by NickPascal-PRO** [comment]
已经发送给您的邮箱

**Comment by hakadao** [comment]
你是想内容那里控制显示宽度吗？
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/33394391/169114946-b42f084d-7af5-415d-a96a-24eda245eeb3.png">
