### ISSUE TITLE
最近的logo变成了一个大B

### ISSUE THREAD

**Issue by AKIs-z01** [hakadao/bilibili-simple-home#41]
![image](https://user-images.githubusercontent.com/51504776/168951871-558b38d5-f5fe-4b08-a783-59ef9d921efc.png)

**Comment by hakadao** [comment]
嗯，在考虑其他解决方案

**Comment by AKIs-z01** [comment]
直接替换成图片会不会好
![bilibili图标](https://user-images.githubusercontent.com/51504776/169098898-d4c9c6ad-9e63-4aa2-8c98-178e491ba808.png)
点

**Comment by hakadao** [comment]
直接换成图片的话不能改变颜色

**Comment by xiaofeiTM233** [comment]
jsdelivr炸了，用vercel就行了，比如我改成我自己的https://cdn.afox.tk/userstyles/fonts/Bilibili_Icon.ttf
@hakadao 采用一下？

**Comment by hakadao** [comment]
> jsdelivr炸了，用vercel就行了，比如我改成我自己的https://cdn.afox.tk/userstyles/fonts/Bilibili_Icon.ttf @hakadao 采用一下？

感谢大佬，今晚我弄一下

**Comment by xiaofeiTM233** [comment]
> > jsdelivr炸了，用vercel就行了，比如我改成我自己的https://cdn.afox.tk/userstyles/fonts/Bilibili_Icon.ttf @hakadao 采用一下？
> 
> 感谢大佬，今晚我弄一下

我给你提个合并吧

**Comment by hakadao** [comment]
> > > jsdelivr炸了，用vercel就行了，比如我改成我自己的https://cdn.afox.tk/userstyles/fonts/Bilibili_Icon.ttf @hakadao 采用一下？
> > 
> > 
> > 感谢大佬，今晚我弄一下
> 
> 我给你提个合并吧

ok

**Comment by xiaofeiTM233** [comment]
> > > > jsdelivr炸了，用vercel就行了，比如我改成我自己的https://cdn.afox.tk/userstyles/fonts/Bilibili_Icon.ttf @hakadao 采用一下？
> > > 
> > > 
> > > 感谢大佬，今晚我弄一下
> > 
> > 
> > 我给你提个合并吧
> 
> ok

合并请求发好了你可以再改一下版本号

**Comment by hakadao** [comment]
v1.6.20 已修正
