### ISSUE TITLE
滚动条

### ISSUE THREAD

**Issue by china5** [hakadao/bilibili-simple-home#42]
全屏壁纸后为什么有滚动台条呢 看着非常难受
![image](https://user-images.githubusercontent.com/90046795/169844955-f72e7900-bc85-4a20-ae4a-0c331abd4265.png)

**Comment by china5** [comment]
以前好像没有的哎

**Comment by hakadao** [comment]
有沒有選擇帶有「不能下滑查看更多視頻」字樣的首頁樣式？

**Comment by hakadao** [comment]
可以，後續加個選項

**Comment by china5** [comment]
好的好的 谢谢
