### ISSUE TITLE
在 1.6.15 版本中毛玻璃效果异常

### ISSUE THREAD

**Issue by InkJadeite** [hakadao/bilibili-simple-home#44]
在 Firefox 102.0b6 版本使用 1.6.15 版本样式时，只有搜索框拥有毛玻璃效果，且在搜索框上存在方形黑色叠加层，而在 1.6.2 版本样式中整个背景拥有模糊效果。
在 360极速x 21.0.1110.0（内核 Chromium 95.0.4638.69 ） 版本中，使用 1.6.15 版本样式时与 Firefox 表现一致，使用 1.6.2 版本样式时毛玻璃效果没有生效。

如下效果
![特写](https://user-images.githubusercontent.com/59567872/173113385-7791583d-05fd-43c4-b3f5-52accc43edda.png)

Firefox 新版脚本
![new_1](https://user-images.githubusercontent.com/59567872/173096815-88a74bf8-27db-4813-bccc-ee82d3af8726.png)
![new_2](https://user-images.githubusercontent.com/59567872/173096803-9167c2d7-6814-428d-90f2-354ca9a4a80e.png)
360 新版脚本
![360_1](https://user-images.githubusercontent.com/59567872/173107537-04841582-e093-4760-b1b4-76c73e98c95a.png)
![360_2](https://user-images.githubusercontent.com/59567872/173107554-f9077e11-6ae2-4a99-95a9-715b1bc8dce1.png)
Firefox 旧版脚本
![old_1](https://user-images.githubusercontent.com/59567872/173096788-f80dbf78-ab3b-4aee-921f-64383965537f.png)
![old_2](https://user-images.githubusercontent.com/59567872/173096829-0c6b8aad-fb77-432e-aa9b-bf53684de11b.png)
360 旧版脚本
![360_old_1](https://user-images.githubusercontent.com/59567872/173102600-052fa03f-5c61-42c6-807f-83d0379fc13b.png)
![360_old_2](https://user-images.githubusercontent.com/59567872/173102584-0369a839-c2ce-4889-9fae-24e9338e9f5c.png)

好像放太多图了

**Comment by hakadao** [comment]
感謝閣下對樣式的支持，Firefox 即使在 `about:config` 啓用了 backdrop-filter 顯示還是有一定的問題，暫時不明白怎麼解決😐
報歉這麼久才答覆

**Comment by InkJadeite** [comment]
不好意思，在360浏览器上使用旧版样式的截图贴错了。
这个问题其实是新旧版本的毛玻璃样式表现不一致，这个不一致的情况在基于 Chromium 的浏览器上也出现了，所以我想这个问题应当和 Firefox 没有关系。
![左为旧版本旧右为新版本](https://user-images.githubusercontent.com/59567872/183357883-f7d4ab5e-a51e-4896-859b-a20e19edbed5.png)
这是在360浏览器上新旧版本的对比，左边为旧版本，右边为新版本。可以看到暗化及模糊范围在新版本被限制在搜索框底部的一个矩形内，而在旧版本则是全屏的。
我不知道哪种是您希望的效果，但无论是哪种效果，新版本的效果确实有BUG。
抱歉，因为高考的原因，我没有及时回复。

**Comment by hakadao** [comment]
已修正，在1.7.1版本下
