### ISSUE TITLE
建议加个设置能够修改用户头像旁边的图标和文字颜色

### ISSUE THREAD

**Issue by xiaofeiTM233** [hakadao/bilibili-simple-home#46]
建议加个设置能够修改胶囊内图标颜色，我都是自己改的
（因为背景需要，背景时白色更好，下滑时黑色更好）
效果
![QQ截图20220708104124](https://user-images.githubusercontent.com/55832499/177906448-2e250a5e-2469-40a5-abc7-e6cae5c78547.png)
![QQ截图20220708104201](https://user-images.githubusercontent.com/55832499/177906477-86643706-6d1c-4aa9-b640-f14cf828594f.png)
我就加了2条
![QQ截图20220708104354](https://user-images.githubusercontent.com/55832499/177906567-23efec91-f378-4142-837d-654533fb6261.png)
其实下面那个可以直接到下面改的，因为更新会覆盖所以我就直接加了个!important下次复制过去就行了

**Comment by hakadao** [comment]
你那边还有回到旧版的设置吗？我记得我首页里只有一个内测首页的按钮，然后我删了一推旧的样式orz，不知道你那边有没有出问题

**Comment by hakadao** [comment]
颜色按照主题色还是自定义？

**Comment by xiaofeiTM233** [comment]
> 

我这边有回到旧版的按钮，但是旧版不喜欢

**Comment by xiaofeiTM233** [comment]
> 颜色按照主题色还是自定义？

颜色我直接白色的，我觉得可以搞成自定义

**Comment by hakadao** [comment]
> > 颜色按照主题色还是自定义？
> 
> 颜色我直接白色的，我觉得可以搞成自定义

自定义是可以，可是会太花。目前的话考虑加个所有状态下黑色、白色、主题色的选项

**Comment by hakadao** [comment]
實現了，報歉拖了那麼久orz
