### ISSUE TITLE
自定义壁纸给b站首页头部广告占领

### ISSUE THREAD

**Issue by RickSanchezy** [hakadao/bilibili-simple-home#48]
![EH{)~RN`5%ZG{OX` _MY9TY](https://user-images.githubusercontent.com/75956223/178111292-cec94e56-3dba-439d-9039-9ed621af6b69.png)
![8SVR6$LHE54WGM}~H){O3WJ](https://user-images.githubusercontent.com/75956223/178111307-7456777f-166b-4005-bc61-1db9e60e77f5.png)

**Comment by hakadao** [comment]
是我的問題，之前我見都我首頁沒有回到舊版首頁之選項後，刪了舊樣式的支援
過後會加回

**Comment by hakadao** [comment]
今後會打算放棄對舊首頁支援，着重新首頁

**Comment by hakadao** [comment]
修正了，v1.6.19版本
