### ISSUE TITLE
显示logo有问题

### ISSUE THREAD

**Issue by XYC1234** [hakadao/bilibili-simple-home#49]
![1658204106929](https://user-images.githubusercontent.com/74289474/179663356-e3d25c60-a4c8-4215-bf6d-1681b8897d9d.png)

**Comment by hakadao** [comment]
重複問題，請移步至 #41 集中討論，抱歉

**Comment by hakadao** [comment]
v1.6.20 已修正

**Comment by xiaofeiTM233** [comment]
事实上是昨天我错把DNS关了才出的问题/捂脸

**Comment by hakadao** [comment]
@xiaofeiTM233 我已經換成我在 vercel 架設的地址了，並且圖示所字體也換了
