### ISSUE TITLE
增加主题色设置项

### ISSUE THREAD

**Issue by Geeyun-JY3** [hakadao/bilibili-simple-home#5]
希望可以有一个自助选择主题色的设置项

**Comment by hakadao** [comment]
主题色是指蓝色或粉红色又或是其他颜色吗？

**Comment by Geeyun-JY3** [comment]
> 主题色是指蓝色或粉红色又或是其他颜色吗？

嗯，就是让这些地方的颜色（目前都是天蓝色）可自定义：
![image](https://user-images.githubusercontent.com/49396421/88304052-54a33200-cd3a-11ea-9e53-06f3bb5cfc05.png)
![image](https://user-images.githubusercontent.com/49396421/88304101-6684d500-cd3a-11ea-8e00-1319c34cebeb.png)

顺便建议让 Logo 图标样式多个粉色的可选项

**Comment by hakadao** [comment]
新版本已经实现

**Comment by Geeyun-JY3** [comment]
这个`选择 Logo 图标样式` 的文案直接写成 `跟随主题颜色` 会不会更好，就是怕有些人对这个「彩色」感到迷惑。
![image](https://user-images.githubusercontent.com/49396421/89289029-2a7e3800-d689-11ea-94b4-343c6e441d80.png)

**Comment by hakadao** [comment]
> 这个`选择 Logo 图标样式` 的文案直接写成 `跟随主题颜色` 会不会更好，就是怕有些人对这个「彩色」感到迷惑。
> ![image](https://user-images.githubusercontent.com/49396421/89289029-2a7e3800-d689-11ea-94b4-343c6e441d80.png)

也对，谢谢提议
