### ISSUE TITLE
换一换按键不显示

### ISSUE THREAD

**Issue by XYC1234** [hakadao/bilibili-simple-home#50]
![image](https://user-images.githubusercontent.com/74289474/186876544-736b05bd-58be-40b8-98bc-d91b76f4fdf3.png)
这里应该有一个换一换的按键，可是不知道为什么不见了

**Comment by hakadao** [comment]
看到了，之前不知道为什么去掉了换一换，今天调一下

**Comment by hakadao** [comment]
已修正
