### ISSUE TITLE
log不显示

### ISSUE THREAD

**Issue by XYC1234** [hakadao/bilibili-simple-home#51]
就是这个背景可以换成图片吗，白色的看着有点难受
![image](https://user-images.githubusercontent.com/74289474/187327403-88f2a33b-87da-47d7-9770-d44d0cc032d4.png)

**Comment by hakadao** [comment]
這一行是原本是推廣影片和廣告地方，廣告我都隱藏了，下版本乾脆直接隱藏這一行算了

**Comment by XYC1234** [comment]
主要是想问下，可以支持把背景换了不
因为首页换成了自定义图片，下滑的时候就有一种说不出的感觉

**Comment by hakadao** [comment]
之前試過，就是很卡，後面版本將這個選項刪了

**Comment by XYC1234** [comment]
那如果把背景设置为纯白了，这样会卡吗

**Comment by hakadao** [comment]
那就没有意义了呀

**Comment by hakadao** [comment]
1.7.3已将空出的一行删除
