### ISSUE TITLE
*.vercel.app 在国内访问被封锁

### ISSUE THREAD

**Issue by w568w** [hakadao/bilibili-simple-home#52]
目前国内仅有极少数地区可直接连接，其他地区（灰色）均无法访问：
![image](https://user-images.githubusercontent.com/8389787/187327275-f544b6a8-34fe-49ff-abcc-bd5353d3a2ee.png)

导致每次上 B 站必须挂着代理，否则就会变成这样：
![image](https://user-images.githubusercontent.com/8389787/187327360-8cb1c54b-aaa4-489e-898a-f9e67f515755.png)

有考虑过更换其他静态资源托管平台，例如 [这里列出的](https://github.com/openstyles/stylus/wiki/Writing-UserCSS#hosting-a-usercss) 或者 [码云 Pages](https://gitee.com/help/articles/4136) 吗？

**Comment by hakadao** [comment]
ummmm, 我打算試試其他平台

**Comment by hakadao** [comment]
现在换回 jsdelivr 了，那里列出的平台基本被 ban 完，码云开源仓库要绑定电话号码操作简直神

**Comment by w568w** [comment]
看起来是解决了，关闭 Issue。

ps: 有没有考虑过出个教程/设置项让用户自托管静态文件呢？

**Comment by hakadao** [comment]
> 看起来是解决了，关闭 Issue。
> 
> ps: 有没有考虑过出个教程/设置项让用户自托管静态文件呢？

好像没有多少人用到吧，建议用户翻墙实际一点orz
