### ISSUE TITLE
现在页面纯白 无法显示背景

### ISSUE THREAD

**Issue by Scat15** [hakadao/bilibili-simple-home#53]

**Comment by hakadao** [comment]
抱歉，暂时没有发现问题，阁下能方便发一下配置选项吗？这样我能更好的排查

**Comment by Scat15** [comment]
![image](https://user-images.githubusercontent.com/37100990/202912868-637a2335-42d2-48e8-a113-6b8a7b6c0e64.png)
![image](https://user-images.githubusercontent.com/37100990/202912881-0440d926-8ca1-45cd-952b-667b18d0bd6b.png)
如下 我重新装过

**Comment by hakadao** [comment]
应该是 sm.ms 墙了原因吧，之前这张壁纸好像放在那个图床里

**Comment by hakadao** [comment]
> 应该是 sm.ms 墙了原因吧，之前这张壁纸好像放在那个图床里

我看看能不能把壁纸放到该项目里面，然后使用 jsdelivr 看看能不能行，实在不行的话我也没有其他对策了

**Comment by Scat15** [comment]
收到， 这些图好像确实是图床问题，但我bing每日也失效了

**Comment by hakadao** [comment]
> 收到， 这些图好像确实是图床问题，但我bing每日也失效了

bing 那里是第三方接口炸了，后续我看看有没有其他方法补救

**Comment by hakadao** [comment]
更新了 1.7.4 版本了, 看看还有没有问题

**Comment by Scat15** [comment]
![image](https://user-images.githubusercontent.com/37100990/203180235-68a24a55-46bc-4d54-a691-86da7dd534cf.png)
好像还是不行 魔法后ok
![image](https://user-images.githubusercontent.com/37100990/203180299-c265bb00-3668-40a9-bf11-8fdc2af0e7a5.png)

**Comment by hakadao** [comment]
试过直连的，我这边可以，orz

**Comment by Scat15** [comment]
> 试过直连的，我这边可以，orz

但我这边还需要魔法后才连得上图床，我试试替换为国内图床？

**Comment by hakadao** [comment]
> > 试过直连的，我这边可以，orz
> 
> 但我这边还需要魔法后才连得上图床，我试试替换为国内图床？

我換了，現在是用jsdelivr，沒用圖床

**Comment by Scat15** [comment]
打不开。。。
![image](https://user-images.githubusercontent.com/37100990/203370486-7abd4628-97f9-4fe2-b571-c4e09caffda4.png)
ying应该是部分地方不给用

**Comment by hakadao** [comment]
我今晚继续看下有没有其他图床吧

**Comment by hakadao** [comment]
换图床了，试试https://s1.ax1x.com/2022/11/23/zGPJu8.jpg

**Comment by Scat15** [comment]
这个图床会删图。。

**Comment by hakadao** [comment]
那还有什么图床推荐
~~讲真我不怎么想为了GFW无理封锁而进行对抗~~

**Comment by Scat15** [comment]
确实挺尬的。。我最初以为是B站改版引起的bug 我现在用的是Z4A 我提一个PULL Request对图片进行替换吧

**Comment by hakadao** [comment]
好吧，开个pull request吧
