### ISSUE TITLE
背景图404

### ISSUE THREAD

**Issue by aboutZZ** [hakadao/bilibili-simple-home#56]
背景图：
- [BML2019 VR](https://s1.imagehub.cc/images/2022/11/24/BML2019_VR.jpg)
- [2020拜年祭活动](https://s1.imagehub.cc/images/2022/11/24/2020PayNewYearsCall.jpg)

都404了

**Comment by hakadao** [comment]
errr我回去看看

**Comment by hakadao** [comment]
已修正 v1.7.5.2
