### ISSUE TITLE
搜索栏的搜索历史看起来有点别扭，能关掉吗？

### ISSUE THREAD

**Issue by dengfengliancui** [hakadao/bilibili-simple-home#57]
自己试着屏蔽，发现会连相关搜索一起屏蔽
![Snipaste_2022-12-09_12-17-51](https://user-images.githubusercontent.com/103981512/206623266-6a56bc9a-f31d-457d-a0c9-e3d2aa2a06c5.png)

**Comment by hakadao** [comment]
抱歉現在才看到，不怎麼想屏蔽因為這是最基本的功能
設計上改變的話可以，如果有更好的設計的話

**Comment by xiaofeiTM233** [comment]
可以自己加
`.history {
display:none;
}`
这样就是，建议自己实操隐藏元素awa
