### ISSUE TITLE
希望能使用动态壁纸作为背景

### ISSUE THREAD

**Issue by 22Frederic** [hakadao/bilibili-simple-home#62]
如题，性能开销大没关系，加入这个选项即可

谢谢作者大大！

**Comment by hakadao** [comment]
其實可以放圖片地址可以用gif的

**Comment by 22Frederic** [comment]
谢谢回复！gif的画质感觉对于电脑屏幕有点不够，而且分辨率帧率高的gif有的甚至比视频还大，个人感觉不合适

**Comment by hakadao** [comment]
如果放视频链接的话该样式不能实现，这是css的限制
