### ISSUE TITLE
1.7.7舊版首頁背景圖失效（新版首頁正常，1.7.7以前版本正常）

### ISSUE THREAD

**Issue by Sakiitum** [hakadao/bilibili-simple-home#63]
![Screenshot 2023-02-01 123511](https://user-images.githubusercontent.com/118611124/215950041-66e79016-6779-455a-9bde-c211689638fc.png)

**Comment by hakadao** [comment]
不是很想維護舊版首頁樣式，因為現在CSS的太大了，之後可能會考慮單獨開一個樣式支援舊版首頁，但不會有功能上的更新

**Comment by xiaofeiTM233** [comment]
解决办法：
1.回退到旧版，然后关闭检查更新![image](https://user-images.githubusercontent.com/55832499/218004503-cf08f2d2-e60d-4498-a28e-02bfafbdf5ad.png)
2.使用新版首页
