### ISSUE TITLE
关闭“LOGO发光效果”导致左上角LOGO变黑

### ISSUE THREAD

**Issue by xiaofeiTM233** [hakadao/bilibili-simple-home#64]
关闭“LOGO发光效果”导致左上角LOGO变黑
![image](https://user-images.githubusercontent.com/55832499/218001802-a5d22cec-6c64-4ace-a45a-683a95015c6a.png)
↑关闭
![image](https://user-images.githubusercontent.com/55832499/218001824-961d3a50-1ba1-401d-a1d1-d2c63c71fb50.png)
↑开启
原因
![image](https://user-images.githubusercontent.com/55832499/218002308-a6a2b1e3-cff1-45d7-84bb-38eddc8d7803.png)
移除此处“#FFF”即可解决

**Comment by hakadao** [comment]
我回去改改orz
