### ISSUE TITLE
首页右上历史菜单问题

### ISSUE THREAD

**Issue by Hleison** [hakadao/bilibili-simple-home#67]
![image](https://user-images.githubusercontent.com/75768458/229359214-38690168-9743-46af-9f3f-27d9a27ca604.png)
历史下拉菜单里的直播，不置顶正在直播的UP，显示全部按钮变成只显示全部历史的页面，而不是显示全部关注的UP直播。

**Comment by Hleison** [comment]
直播菜单的<查看全部>按钮，变成了显示历史视频。

**Comment by hakadao** [comment]
原版主頁也是這樣的

**Comment by Hleison** [comment]
我的不是哎，在直播栏下点击的<查看全部>按钮，是跳转到 我的关注-个人中心 这个页面。

**Comment by hakadao** [comment]
那是動態彈窗，歷史的查看全部是跳轉到歷史列表的
