### ISSUE TITLE
首页自定义图片模糊

### ISSUE THREAD

**Issue by TanezakiAtsum1** [hakadao/bilibili-simple-home#68]
背景图模糊，在生成url地址时选择缩放分辨率后也没效果
![反馈](https://github.com/hakadao/bilibili-simple-home/assets/107610383/9913dc55-d6c7-46c1-bdc6-dd1feef3eb36)

**Comment by hakadao** [comment]
用哪个图床上传的，图片处理样式并没有调整

**Comment by TanezakiAtsum1** [comment]
> 

Postimages

**Comment by TanezakiAtsum1** [comment]
https://postimages.org/

**Comment by hakadao** [comment]
试试 https://imgchr.com/ 或 sm.ms

**Comment by TanezakiAtsum1** [comment]
已解决，谢谢
