### ISSUE TITLE
自定义背景实现方式建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [hakadao/bilibili-simple-home#7]
UserCSS 版和 Userstyle.org 版本相比不能使用自己上传的自定义背景，是找不到实现方式？
自定义背景的实现方式可以参考 [weibo-lite](https://github.com/tolking/usercss/blob/master/weibo-lite/README.md)（或该样式作者另一样式 [bilibili-lite](https://github.com/tolking/usercss/blob/master/bilibili-lite/README.md)），用 `Text Input` 控件来实现。
![image](https://user-images.githubusercontent.com/49396421/88608779-24022600-d0b5-11ea-8403-db493cb501cb.png)

**Comment by hakadao** [comment]
弄了那么久居然没有注意到，可能是我对背景没有太大需求，下版本会尝试一下

**Comment by Geeyun-JY3** [comment]
> 弄了那么久居然没有注意到，可能是我对背景没有太大需求，下版本会尝试一下

其实我也没有这个需求🤣

**Comment by 1235789gzy1** [comment]
我直接跑代码里头替换了链接23333（自定义狂热粉）

**Comment by hakadao** [comment]
已实现

**Comment by 1235789gzy1** [comment]
有自定义搜索框背景，那么有没有主站背景呢awa？
![image](https://user-images.githubusercontent.com/52618207/89405522-4d265480-d74e-11ea-8322-9e083106327c.png)

**Comment by hakadao** [comment]
@1235789gzy1 搜索框背景和主站背景同时设置会很奇怪，看起来也不怎么舒服
