### ISSUE TITLE
首页图片可下滑会有一个横向的滚动条

### ISSUE THREAD

**Issue by Bingo-QAQ** [hakadao/bilibili-simple-home#71]
![屏幕截图 2023-12-16 194257](https://github.com/hakadao/bilibili-simple-home/assets/86760806/583dddf4-2a08-45dd-b33a-27287f25aadc)

**Comment by hakadao** [comment]
好，我回去看看，~~好久都沒有看這個項目了，現在用的是BewlyBewly你可以看見~~

**Comment by hakadao** [comment]
這是下載插件導致出現橫條吧
