### ISSUE TITLE
安装链接有问题

### ISSUE THREAD

**Issue by 24kcsplus** [hakadao/bilibili-simple-home#9]
刚刚去翻了下xStyle官方文档，链接前面要加上`https://ext.firefoxcn.net/xstyle/install/open.html?name=StyleName&code=`
希望作者能及时更改README.md。希望不要影响到后浪（手动狗头

**Comment by hakadao** [comment]
emmmm，我看看。

**Comment by hakadao** [comment]
默认是stylus插件安装，xStyle只是备选项，回去研究一下

**Comment by 24kcsplus** [comment]
ok，刚刚才注意到
（我这个丈育才发现自己安装的是Stylish

**Comment by 24kcsplus** [comment]
话说作者不打算整个备选的安装链接吗？

**Comment by hakadao** [comment]
会弄的

**Comment by hakadao** [comment]
新版本已更新
